enabled: true
debug: false
log:
  enabled: true
  folder: logs
  rotate_daily: true
  include_stacktraces: false
fix:
  close_on_zmenu_disable: true
  close_all_inventories: true
  async_guard: true
  notify_players: false
  notify_message: "&eYour menu was closed due to zMenu restart."
